export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"home"},["/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"幻灯片页","i":"person-chalkboard"},[":md"]],
  ["v-1d59d0e6","/md/resume.html",{"y":"a","t":"个人简历","i":"laptop-code","I":0},[":md"]],
  ["v-e9a6f638","/md/dev-log/Note01.html",{"y":"a","t":"Note01","i":"laptop-code","I":0},[":md"]],
  ["v-e63d44fa","/md/dev-log/Note02.html",{"y":"a","t":"Note02","i":"laptop-code","I":0},[":md"]],
  ["v-e2d393bc","/md/dev-log/Note03.html",{"y":"a","t":"Note03","i":"laptop-code","I":0},[":md"]],
  ["v-df69e27e","/md/dev-log/Note04.html",{"y":"a","t":"Note04","i":"laptop-code","I":0},[":md"]],
  ["v-dc003140","/md/dev-log/Note05.html",{"y":"a","t":"Note05","i":"laptop-code","I":0},[":md"]],
  ["v-d8968002","/md/dev-log/Note06.html",{"y":"a","t":"Note06","i":"laptop-code","I":0},[":md"]],
  ["v-d52ccec4","/md/dev-log/Note07.html",{"y":"a","t":"Note07","i":"laptop-code","I":0},[":md"]],
  ["v-d1c31d86","/md/dev-log/Note08.html",{"y":"a","t":"Note08","i":"laptop-code","I":0},[":md"]],
  ["v-ce596c48","/md/dev-log/Note09.html",{"y":"a","t":"Note09","i":"laptop-code","I":0},[":md"]],
  ["v-834430f4","/md/dev-log/Note10.html",{"y":"a","t":"Note10","i":"laptop-code","I":0},[":md"]],
  ["v-7c27fd02","/md/dev-log/",{"y":"a","t":"开发日志","i":"laptop-code"},["/md/dev-log/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-2d0aa3df","/md/",{"y":"p","t":"Md"},[]],
]
